from flask import Flask, render_template, request  # type: ignore
from flask_socketio import SocketIO

from .settings import Settings
from .context.contextManager import ContextManager
from .ai_chat_generator import AiChatGenerator
from .message import Message
from .slm_chat_logger import Logger

from typing import TYPE_CHECKING

# Handle Flask request object type checking
if TYPE_CHECKING:
    from flask import Request as _Request

    class Request(_Request):
        sid: str
        namespace: str
        remote_addr: str

    request: Request


class Application:
    def __init__(self):
        """
        Initialize the Flask application and SocketIO server.

        Parameters
        ----------
        logger : logging.Logger, optional
            A logger instance for logging messages. If None, a default logger is created.
        """

        self.app = Flask(__name__)
        with self.app.app_context():
            self.socketio = SocketIO(self.app)
            Logger.info("Initializing application")

            self.messages: list[Message] = []
            self.reset_messages()
            self.clients = {}
            self.ai_chat_generator = AiChatGenerator(self.slm_token_callback, self.slm_finish_callback)
            self.ai_chat_target_index = None
            self.ai_busy = False
            self.user_count = 0
            self.ai_enabled = True

            if Settings.get("context_modules"):
                ContextManager.register_context_modules(Settings.get("context_modules"))

            self.make_routes()
            Logger.info(f"Application initialized with model: {Settings.get('model')} on port {Settings.get('port')}")

    def reset_messages(self) -> None:
        """
        Reset the messages list and initialize the system prompt message.
        """
        self.messages = [Message("system", Settings.get("system_prompt"), 0, None, Settings.get("hide_system_prompt"))]
        self.messageId = 1
        if Settings.get("greeting") and Settings.get("greeting") != "":
            self.add_message("assistant", Settings.get("greeting"))

    def slm_token_callback(self, new_content: str, full_response: str) -> None:
        """
        Updates the AI message indicated by `ai_chat_target_index` with the new content generated by the AI model.
        Updates clients by appending the new content to the existing message.

        Parameters
        ----------
        new_content : str
            The new tokens generated by the AI model.
        full_response : str
            The full response generated so far.
        """
        if self.ai_chat_target_index is None:
            Logger.warning("AI chat target index is None, cannot update message")
            return
        self.messages[self.ai_chat_target_index].content = full_response
        self.update_clients_append(self.messages[self.ai_chat_target_index].id, new_content)

    def slm_finish_callback(self, full_response: str) -> None:
        """
        Callback function for when the AI model finishes generating a response.
        Updates clients with the final response, if hasn't been deleted.
        """
        # Update message only if an index exists. The referenced message may have been deleted.
        if self.ai_chat_target_index is not None:
            self.messages[self.ai_chat_target_index].content = full_response
            self.update_clients([self.messages[self.ai_chat_target_index].id])
        self.set_ai_busy(False)
        Logger.info(f"AI response completed: {full_response}")

    def request_slm_background_response(self):
        """
        Request a background response for the current messages from the AI model.
        """
        Logger.info("Requesting AI response")
        if not self.ai_enabled:
            Logger.warning("AI responses are disabled, not requesting response")
        elif self.ai_chat_generator.request_background_chat(self.messages):
            self.add_message("assistant", "...")
            self.ai_chat_target_index = len(self.messages) - 1
            self.set_ai_busy(True)
        else:
            Logger.warning("Failed to request AI response - model may be busy")

    def add_message(self, role, content, user_id=None, hidden=False):
        self.messages.append(Message(role, content, self.messageId, user_id, hidden))
        Logger.debug(f"Added {role} message: {content}, ID: {self.messageId}, User ID: {user_id}, Hidden: {hidden}")
        self.messageId += 1

    def update_clients_append(self, messageId, content_to_append, clientIds=None):
        """
        Append data to the clients.

        Parameters
        ----------
        messageId : int
            ID of the message to update.
        content_to_append : str
            Content to append to the message.
        clientIds : list of int, optional
            List of client IDs to send the messages to. If None, all clients are updated.
        """
        data = [self.messages[messageId].to_dict(Settings.get("show_user_name"))]
        data[0]["content"] = content_to_append
        data[0]["append"] = True
        clientIds = clientIds or self.clients.keys()

        if messageId >= len(self.messages) or not self.messages[messageId]:
            Logger.warning(f"Message ID {messageId} not found, not appending")
            return
        elif self.messages[messageId].hidden:
            Logger.warning(f"Message ID {messageId} is hidden, not appending")
            return

        for clientId in clientIds:
            if clientId in self.clients:
                self.socketio.emit("update_messages", {"messages": data}, to=clientId)
            else:
                Logger.warning(f"Client ID {clientId} not found in clients list")

        Logger.debug(f'Appended data "{content_to_append}" to clients {clientIds}')

    def update_clients(self, messageIds=None, clientIds=None):
        """
        Update clients with new messages.

        Parameters
        ----------
        messageIds : list of int
            Message IDs to send to the clients. If None, the last message ID is used.
        clientIds : list of int
            List of client IDs to send the messages to. If None, all clients are updated.
        append : bool
            If True, indicates that the message content should be appended to the existing messages.
        """
        clientIds = clientIds or self.clients.keys()
        messageIds = messageIds or [self.messageId - 1]
        for clientId in clientIds:
            if clientId in self.clients:
                updated_messages = []
                for message in self.messages:
                    if message.id in messageIds and not message.hidden:
                        updated_messages.append(message.to_dict(Settings.get("show_user_name")))

                if updated_messages:
                    self.socketio.emit("update_messages", {"messages": updated_messages}, to=clientId)

        if messageIds:
            Logger.debug(f"Updated clients with message IDs: {messageIds}")

    def broadcast_user_count(self):
        """Broadcast the current user count to all clients"""
        self.socketio.emit("user_count", {"count": self.user_count})
        Logger.debug(f"User count updated: {self.user_count}")

    def set_ai_busy(self, busy):
        """Set AI busy status and broadcast to all clients"""
        self.ai_busy = busy
        self.socketio.emit("ai_status", {"busy": self.ai_busy})
        if busy:
            Logger.debug("AI status set to busy")
        else:
            Logger.debug("AI status set to idle")

    def toggle_ai(self, enabled):
        """Toggle AI responses and broadcast to all clients"""
        self.ai_enabled = enabled
        self.socketio.emit("ai_toggle_status", {"enabled": self.ai_enabled})
        Logger.info(f"AI responses {'enabled' if enabled else 'disabled'}")

    def reset_clients(self):
        """Reset all clients by sending them the current messages"""
        for clientId in self.clients:
            self.socketio.emit("reset", to=clientId)
        Logger.info("Chat reset for all clients")

    def make_routes(self):
        @self.app.route("/slm-chat/")
        def index():
            return render_template("index.html")

        @self.socketio.on("connect")
        def handle_connect(auth=None):
            """Client connection"""
            Logger.info(f"Client connected: {request.sid} {request.remote_addr}")
            self.clients[request.sid] = request.namespace
            self.user_count += 1
            self.broadcast_user_count()
            self.update_clients(range(self.messageId))
            self.socketio.emit("ai_status", {"busy": self.ai_busy}, to=request.sid)
            self.socketio.emit("ai_toggle_status", {"enabled": self.ai_enabled}, to=request.sid)

        @self.socketio.on("disconnect")
        def handle_disconnect():
            """Client disconnect"""
            Logger.info(f"Client disconnected: {request.sid}")
            if request.sid in self.clients:
                del self.clients[request.sid]
                self.user_count -= 1
                self.broadcast_user_count()

        @self.socketio.on("submit_message")
        def handle_message(data):
            """Handles message submission from the client."""
            Logger.info(f"Message from {request.sid}: {data}")
            content = data.get("content", "")

            hidden = False
            if content == "":
                Logger.info(f"Received empty message from {request.sid}. Assuming forced response.")
                content = Settings.get("force_prompt")
                hidden = True

            self.add_message("user", content, request.sid, hidden)
            self.update_clients([self.messageId - 1])
            self.request_slm_background_response()

        @self.socketio.on("toggle_ai")
        def handle_toggle_ai(data):
            """Handles toggling AI on/off."""
            Logger.info(f"Toggle AI request from {request.sid}: {data}")
            enabled = data.get("enabled", True)
            self.toggle_ai(enabled)

        @self.socketio.on("reset")
        def handle_reset():
            """Handles reset chat request from the client."""
            Logger.info(f"Reset request from {request.sid}")
            self.reset_messages()
            self.ai_chat_target_index = None
            self.ai_chat_generator.cancel_generation()
            self.set_ai_busy(False)
            self.reset_clients()
            self.update_clients()

        @self.socketio.on("pull_messages")
        def handle_pull_messages(data={}):
            """Handles message pull request from the client."""
            Logger.debug(f"Pull messages request from {request.sid}")
            id = data.get("id")
            if not id:
                self.update_clients(clientIds=[request.sid])
            else:
                self.update_clients(messageIds=[id], clientIds=[request.sid])

        @self.socketio.on("reset_context")
        def handle_reset_context():
            """Handles resetting AI context request from the client."""
            Logger.info(f"Reset context request from {request.sid}")
            self.add_message("assistant", "Let me take a moment to read the context that will be sent. I'll tell you what I understood from it.", "assistant")
            self.add_message("user", ContextManager.get_context(), "context", True)
            self.update_clients(messageIds=[self.messageId - 2, self.messageId - 1])
            self.request_slm_background_response()

    def run(self):
        """
        Run the Flask application with SocketIO.
        """
        if Settings.get("debug"):
            Logger.info(f"Starting server in DEBUG mode on port {Settings.get('port')}")
            self.socketio.run(self.app, host="127.0.0.1", port=Settings.get("port"), debug=True)
        else:
            Logger.info(f"Starting server in PRODUCTION mode on port {Settings.get('port')}")
            self.socketio.run(self.app, host="0.0.0.0", port=Settings.get("port"), debug=False)
