import hashlib
import os

from .settings import Settings

ADJECTIVES_PATH = "english/adjectives.txt"
NOUNS_PATH = "english/nouns.txt"


class NameGenerator:
    """
    A singleton class that generates unique names based on a seed string.
    The names are generated by combining a randomly selected adjective and noun
    from predefined lists.
    """

    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self):
        self.adjectives = self._load_words(ADJECTIVES_PATH)
        self.nouns = self._load_words(NOUNS_PATH)

    def _load_words(self, path):
        words = []
        path = os.path.join(Settings.get_root(), path)
        with open(path, "r") as file:
            words = file.read().splitlines()
        return words

    @classmethod
    def generate_name(cls, seed: str) -> str:
        """
        Generate a unique name based on the provided seed, in the format of
        "AdjectiveNoun".

        Parameters
        ----------
        seed : str
            The seed used to generate the name. This can be any string, such as
            a user ID or a random string.

        Returns
        -------
        str
            A unique name generated from the seed. The name consists of a
            randomly selected adjective and noun, both capitalized.
        """
        hash_value = int(hashlib.sha256(seed.encode()).hexdigest(), 16)
        adjective = cls().adjectives[hash_value %
                                     len(cls().adjectives)].capitalize()
        noun = cls().nouns[hash_value % len(cls().nouns)].capitalize()
        return adjective + noun
